version: 1.2
workflows:
   - name: cnest_part0
     subclass: WDL
     primaryDescriptorPath: /wdl/cnest_part0.wdl
   - name: cnest_part1
     subclass: WDL
     primaryDescriptorPath: /wdl/cnest_part1.wdl
   - name: cnest_part2
     subclass: WDL
     primaryDescriptorPath: /wdl/cnest_part2.wdl
   - name: cnest_part3
     subclass: WDL
     primaryDescriptorPath: /wdl/cnest_part3.wdl
   - name: cnest_part4
     subclass: WDL
     primaryDescriptorPath: /wdl/cnest_part4.wdl

